#!/usr/bin/env bash
#
# qa-ai — new team member onboarding wizard.
# Walks you through every credential and tool the QA skills need:
# Python environment, .env secrets, and the Claude Code MCP servers.
#
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Flags
# ──────────────────────────────────────────────────────────────────────────

DRY_RUN=0
for arg in "$@"; do
  [[ "$arg" == "--test" ]] && DRY_RUN=1
done

# ──────────────────────────────────────────────────────────────────────────
# Wizard library
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

TOTAL_STAGES=0
_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()
WRITTEN_MCP=()
SKIPPED=()

_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  if (( DRY_RUN )); then
    printf '%s  --test mode: values will be collected but nothing will be written.%s\n\n' "$YELLOW" "$RESET"
  fi
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

say()  { printf '  %s\n' "$1"; }
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview      >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open     >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open         >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit manually: $url"
}

pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

_existing_env() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing_env "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing_env "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

write_env() {
  local key="$1" value="$2" tmp
  if (( DRY_RUN )); then
    printf '  %s[dry-run]%s would write %s → %s\n' "$YELLOW" "$RESET" "$key" "$ENV_FILE"
    return
  fi
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

finish() {
  _clear
  printf '\n%s%s  ✓ Onboarding complete!%s\n' "$BOLD" "$GREEN" "$RESET"
  printf '\n'
  (( ${#WRITTEN_ENV[@]} ))  && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
  note "Next: open the project in Kiro IDE — MCPs connect automatically on startup."
  note "Run tests: .venv/bin/pytest --env=sit --tenant=aqx --admin"
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

# ── Helpers for this project ──────────────────────────────────────────────

MCP_LIST_CACHE=""

# The VS Code extension ships its own CLI but never puts it on PATH, so
# `command -v claude` fails on a machine that is perfectly able to run it.
# Resolve the binary once; everything below calls "$CLAUDE_BIN".
CLAUDE_BIN=""
_find_claude() {
  if command -v claude >/dev/null 2>&1; then CLAUDE_BIN="claude"; return 0; fi
  local c
  for c in "$HOME/.local/bin/claude" "$HOME/.claude/local/claude"; do
    [[ -x "$c" ]] && { CLAUDE_BIN="$c"; return 0; }
  done
  # Several extension versions sit side by side. Take the newest by mtime —
  # lexical order gets 2.1.9 vs 2.1.10 wrong.
  for c in "$HOME"/.vscode*/extensions/anthropic.claude-code-*/resources/native-binary/claude; do
    [[ -x "$c" ]] || continue
    [[ -z "$CLAUDE_BIN" || "$c" -nt "$CLAUDE_BIN" ]] && CLAUDE_BIN="$c"
  done
  [[ -n "$CLAUDE_BIN" ]]
}

# Filled once at startup. Never call this inside a pipeline — the subshell
# would throw the result away and re-run the (slow) health check every time.
_mcp_refresh() {
  [[ -n "$CLAUDE_BIN" ]] || return 0
  MCP_LIST_CACHE=$("$CLAUDE_BIN" mcp list 2>/dev/null || true)
}

# Registered under this name, healthy or not.
_mcp_registered() {
  local line
  while IFS= read -r line; do
    case "$line" in "$1: "*) return 0 ;; esac
  done <<_MCPLIST
$MCP_LIST_CACHE
_MCPLIST
  return 1
}

# Registered AND passing its health check. A server that is listed but broken
# (bad key, needs auth) is not "done" — the stage must be offered again.
_mcp_has() {
  local line
  while IFS= read -r line; do
    case "$line" in
      "$1: "*)
        case "$line" in *Connected*) return 0 ;; esac
        return 1 ;;
    esac
  done <<_MCPLIST
$MCP_LIST_CACHE
_MCPLIST
  return 1
}

# --fresh rehearses the full flow on an already-configured machine: pretend
# nothing is set up so every stage runs. Forces dry-run, so it can never write.
FRESH=0
for arg in "$@"; do
  [[ "$arg" == "--fresh" ]] && { FRESH=1; DRY_RUN=1; }
done

# gh readiness, in one place so --fresh can override it.
_gh_ready() { command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; }

# This wizard is for a human at a keyboard: it asks you to paste secrets and
# waits for Enter. Run non-interactively and every `read` returns empty, so
# blank values would overwrite a good .env. Refuse unless --test.
if [[ ! -t 0 ]] && (( ! DRY_RUN )); then
  printf '\n  This wizard needs a real terminal — it asks you to paste secrets.\n'
  printf '  Please run it yourself:  ./onboarding.sh\n'
  printf '  (An AI assistant cannot run this on your behalf.)\n\n'
  exit 1
fi

# Overrides the library's banner, whose "Ready to start?" only waits for
# Enter. Showing [yes/no] has to mean it, so "no" exits cleanly.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  if (( DRY_RUN )); then
    printf '%s  --test mode: values will be collected but nothing will be written.%s\n\n' "$YELLOW" "$RESET"
  fi
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n\n' "$RESET"
  local reply=""
  printf '  %sReady to start?%s [yes/no] ' "$BOLD" "$RESET"
  read -r reply || true
  case "$reply" in
    ""|[Yy]|[Yy][Ee][Ss]) ;;
    *) printf '\n  No problem — run ./onboarding.sh whenever you are ready.\n\n'; exit 0 ;;
  esac
}

# Overrides the library's ask_secret, which echoes nothing at all while you
# type. Shows one * per character so you can see the paste landed.
ask_secret() {
  local key="$1" prompt="$2" current input="" char
  current=$(_existing_env "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  if [[ -t 0 ]]; then
    while IFS= read -r -s -n1 char; do
      [[ -z "$char" ]] && break
      if [[ "$char" == $'\177' || "$char" == $'\b' ]]; then
        [[ -n "$input" ]] && { input="${input%?}"; printf '\b \b'; }
        continue
      fi
      # -n1 bypasses the terminal's line editing, so stray control bytes
      # (Ctrl-D, escape sequences) would land inside the secret. Drop them.
      [[ "$char" == [[:cntrl:]] ]] && continue
      input="${input}${char}"
      printf '*'
    done
  else
    read -rs input || true
  fi
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# have_key "a Figma token" — user says they already hold it, so skip the
# walkthrough and go straight to pasting.
have_key() {
  local reply=""
  printf '  %s? %sDo you already have %s? [y/N] ' "$YELLOW" "$RESET" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# reconfigure "Testmo" — a working setup was detected. Never skip a stage
# without asking: say what was found, then let the user decide.
reconfigure() {
  local reply=""
  printf '  %s✓%s %s already looks set up on this machine.\n' "$GREEN" "$RESET" "$1"
  printf '  %s? %sGo through it again anyway? [y/N] ' "$YELLOW" "$RESET"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# already_env KEY — a value is already saved in .env
already_env() { [[ -n "$(_existing_env "$1" 2>/dev/null || true)" ]]; }

# --test should describe what it would do, not open eight browser tabs.
open_url() {
  if (( DRY_RUN )); then
    printf '  %s[dry-run]%s would open %s\n' "$YELLOW" "$RESET" "$1"
    return 0
  fi
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$1"
  { if   command -v wslview      >/dev/null 2>&1; then wslview "$1"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$1"
    elif command -v xdg-open     >/dev/null 2>&1; then xdg-open "$1"
    elif command -v open         >/dev/null 2>&1; then open "$1"
    else warn "couldn't open a browser; visit manually: $1"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit manually: $1"
}

# add_mcp NAME [-e KEY=VAL ...] -- command args...
CLAUDE_MISSING_TOLD=0
add_mcp() {
  local name="$1"; shift
  if [[ -z "$CLAUDE_BIN" ]]; then
    # Four servers go through here. Explain once, then just note the skips.
    if (( CLAUDE_MISSING_TOLD )); then
      note "$name skipped — Claude Code not found."
    else
      warn "Claude Code was not found, so no tool can be connected."
      note "Install it, then re-run this wizard:"
      note "    brew install --cask claude-code"
      note "Already have the VS Code extension? Re-run this from its built-in"
      note "terminal, or any terminal where 'claude' works."
      CLAUDE_MISSING_TOLD=1
      SKIPPED+=("install Claude Code, then re-run ./onboarding.sh to connect the tools")
    fi
    return 0
  fi
  if _mcp_has "$name"; then
    note "$name is already connected — leaving it alone."
    return 0
  fi
  if _mcp_registered "$name"; then
    note "$name is registered but not connecting — replacing it."
    (( DRY_RUN )) || "$CLAUDE_BIN" mcp remove -s user "$name" >/dev/null 2>&1 || true
  fi
  if (( DRY_RUN )); then
    printf '  %s[dry-run]%s would connect %s\n' "$YELLOW" "$RESET" "$name"
    return 0
  fi
  if "$CLAUDE_BIN" mcp add -s user "$name" "$@" >/dev/null 2>&1; then
    printf '  %s✓ connected%s %s\n' "$GREEN" "$RESET" "$name"
    MCP_LIST_CACHE="$MCP_LIST_CACHE
${name}: just added - Connected"
    WRITTEN_MCP+=("$name")
  else
    warn "could not connect $name — you can add it later"
    SKIPPED+=("MCP server: $name")
  fi
}

# set_config "Label" VALUE  — fills a `<FILL_IN>` in project-config.md
set_config() {
  if (( DRY_RUN )); then
    printf '  %s[dry-run]%s would set %s in project-config.md\n' "$YELLOW" "$RESET" "$1"
    return 0
  fi
  python3 - "$1" "$2" <<'PYEOF'
import sys, pathlib
label, value = sys.argv[1], sys.argv[2]
p = pathlib.Path(".claude/steering/project-config.md")
s = p.read_text()
old = "%s: `<FILL_IN>`" % label
if old not in s:
    print("  already filled in — leaving it alone."); raise SystemExit(0)
p.write_text(s.replace(old, "%s: `%s`" % (label, value)))
print("  ✓ saved %s" % label)
PYEOF
}

# Overrides the library's finish() — that one is written for a pytest project.
finish() {
  _clear
  printf '\n%s%s  ✓ All done!%s\n\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]:-0} )) && note "saved ${#WRITTEN_ENV[@]} secret(s) to $ENV_FILE"
  (( ${#WRITTEN_MCP[@]:-0} )) && note "connected ${#WRITTEN_MCP[@]} MCP server(s): ${WRITTEN_MCP[*]}"
  if (( ${#SKIPPED[@]:-0} )); then
    printf '\n'; warn "left for you to finish by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n  %sYou are ready.%s Start Claude Code in this folder and ask, in\n' "$BOLD" "$RESET"
  say "plain English, for what you need:"
  printf '\n      %sgenerate TCs for AO-306%s\n' "$BOLD" "$RESET"
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

_find_claude || true
# claude mcp list starts every configured server and waits for each handshake
# — 20s+ with a dozen of them, and it prints nothing. Say so, or the blank
# screen reads as a hang. banner() clears this a moment later.
if [[ -n "$CLAUDE_BIN" ]]; then
  printf '\n  %sChecking which tools are already connected (about 20 seconds) ...%s\n' "$DIM" "$RESET"
fi
_mcp_refresh
if (( FRESH )); then
  already_env()     { return 1; }
  _mcp_has()        { return 1; }
  _mcp_registered() { return 1; }
  _gh_ready()       { return 1; }
  printf '\n  %s--fresh: pretending nothing is set up. Nothing will be written.%s\n' "$YELLOW" "$RESET"
fi
banner "qa-ai — new team member setup"

# ── Stage 1: Python ───────────────────────────────────────────────────────
stage "Python environment"
say "This installs the small Python programs the QA skills run for you."
say "Nothing to look up — just watch it finish."
printf '\n'
if [[ -d ".venv" ]]; then
  note ".venv already exists — reusing it."
else
  say "Creating .venv ..."
  if (( DRY_RUN )); then
    printf '  %s[dry-run]%s would create .venv\n' "$YELLOW" "$RESET"
  else
    python3 -m venv .venv
    printf '  %s✓ created%s .venv\n' "$GREEN" "$RESET"
  fi
fi
say "Installing dependencies (about a minute) ..."
if (( DRY_RUN )); then
  printf '  %s[dry-run]%s would pip install -r requirements.txt\n' "$YELLOW" "$RESET"
elif .venv/bin/pip install --quiet -r requirements.txt; then
  printf '  %s✓ installed%s\n' "$GREEN" "$RESET"
else
  warn "install failed — check the output above."
  SKIPPED+=("pip install -r requirements.txt")
fi
pause

# ── Stage 2: Jira ─────────────────────────────────────────────────────────
stage "Jira"
say "Lets the assistant read tickets and file bugs as you."
say "Takes about 30 seconds."
printf '\n'
if already_env JIRA_API && ! reconfigure "Jira"; then
  note "Keeping the Jira token already saved."
else
  ask JIRA_EMAIL "Your Atlassian email:"
  printf '\n'
  if ! have_key "a Jira API token"; then
    open_url "https://id.atlassian.com/manage-profile/security/api-tokens"
    step "Click 'Create API token'."
    step "Name it 'qa-ai', click Create, then copy it."
    note "(It is shown only once — copy it before closing.)"
    printf '\n'
  fi
  ask_secret JIRA_API "Paste the token:"
  write_env JIRA_EMAIL "$JIRA_EMAIL"
  write_env JIRA_API   "$JIRA_API"
fi
pause

# ── Stage 3: Google ───────────────────────────────────────────────────────
stage "Google Sheets"
if already_env GOOGLE_REFRESH_TOKEN && _mcp_has google-docs && ! reconfigure "Google Sheets"; then
  note "Keeping the Google setup already in place."
else
  say "Used to export test cases into the team spreadsheet."
  say "It needs a Client ID and a Client Secret from your team lead. The"
  say "third value, a refresh token, is created for you in the browser."
  printf '\n'
  # The Client ID and Secret are not the user's to create — they belong to the
  # shared project. Ask first, and if the answer is no, say where to get them
  # rather than demanding a value the user cannot produce.
  GOOGLE_READY=1
  if ! have_key "the Google Client ID and Client Secret"; then
    say "They belong to the team's shared Google Cloud project, not to your"
    say "own account. Two ways to get them:"
    step "Ask your team lead to send you both values. This is the normal route."
    step "Or, if you already have access to the shared Google Cloud project:"
    open_url "https://console.cloud.google.com/apis/credentials"
    note "     Pick the shared project in the picker (top left)."
    note "     Open the existing entry under 'OAuth 2.0 Client IDs', or make"
    note "     one: Create credentials → OAuth client ID → Desktop app."
    note "     Copy the Client ID and the Client secret it shows."
    note "     Drive, Docs and Sheets APIs must be enabled on that project."
    printf '\n'
    if ! confirm "Do you have both values in front of you now?"; then
      GOOGLE_READY=0
    fi
  fi
  if (( GOOGLE_READY )); then
    ask        GOOGLE_CLIENT_ID     "Google Client ID:"
    ask_secret GOOGLE_CLIENT_SECRET "Google Client Secret:"
    write_env GOOGLE_CLIENT_ID     "$GOOGLE_CLIENT_ID"
    write_env GOOGLE_CLIENT_SECRET "$GOOGLE_CLIENT_SECRET"
    printf '\n'
    if ! have_key "a Google refresh token"; then
      say "Now authorise your own account, once. Your browser opens, you sign"
      say "in, and the token is saved for you — nothing to copy or paste."
      printf '\n'
      if (( DRY_RUN )); then
        printf '  %s[dry-run]%s would run scripts/google_auth.py\n' "$YELLOW" "$RESET"
      elif .venv/bin/python scripts/google_auth.py; then
        # The script writes .env itself; record it so finish() counts it.
        WRITTEN_ENV+=("GOOGLE_REFRESH_TOKEN" "GOOGLE_SHEETS_REFRESH_TOKEN")
      else
        printf '\n'
        warn "Automatic sign-in did not work."
        note "SETUP.md section 2 has the manual route via the OAuth Playground."
        SKIPPED+=("Google refresh token — see SETUP.md section 2")
      fi
    else
      ask_secret GOOGLE_REFRESH_TOKEN "Paste the Refresh token:"
      write_env GOOGLE_REFRESH_TOKEN        "$GOOGLE_REFRESH_TOKEN"
      write_env GOOGLE_SHEETS_REFRESH_TOKEN "$GOOGLE_REFRESH_TOKEN"
      note "(Saved twice — two scripts read it under different names.)"
    fi
    add_mcp google-docs \
      -e "GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID" \
      -e "GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET" \
      -- npx -y @a-bonus/google-docs-mcp
  else
    warn "Skipping Google — those two values have to come from your team lead."
    note "Nothing was changed. Re-run this wizard once you have them."
    SKIPPED+=("Google Sheets: get the Client ID and Client Secret from your team lead, then re-run ./onboarding.sh")
  fi
fi
pause

# ── Stage 4: Testmo ───────────────────────────────────────────────────────
stage "Testmo"
if _mcp_has testmo && ! reconfigure "Testmo"; then
  note "Keeping the Testmo connection already in place."
else
  say "Our test case tool. The assistant reads and writes cases there."
  say "No account yet? Ask your team lead to create one before continuing."
  printf '\n'
  if ! have_key "a Testmo API key"; then
    open_url "https://aquariux.testmo.net"
    step "Log in → your avatar (top right) → API keys → Add API key."
    step "Name it 'qa-ai' and copy the key."
    printf '\n'
  fi
  ask        TESTMO_URL      "Testmo URL [https://aquariux.testmo.net]:"
  [[ -z "$TESTMO_URL" ]] && TESTMO_URL="https://aquariux.testmo.net"
  ask_secret TESTMO_API_KEY  "Testmo API key:"
  ask        TESTMO_EMAIL    "Testmo login email:"
  ask_secret TESTMO_PASSWORD "Testmo password:"
  add_mcp testmo \
    -e "TESTMO_URL=$TESTMO_URL" -e "TESTMO_API_KEY=$TESTMO_API_KEY" \
    -e "TESTMO_EMAIL=$TESTMO_EMAIL" -e "TESTMO_PASSWORD=$TESTMO_PASSWORD" \
    -- npx -y @aqx-qa/testmo-mcp
fi
pause

# ── Stage 5: Figma ────────────────────────────────────────────────────────
stage "Figma"
if _mcp_has figma && ! reconfigure "Figma"; then
  note "Keeping the Figma connection already in place."
else
  say "Lets the assistant read designs when it writes test cases."
  printf '\n'
  if ! have_key "a Figma personal access token"; then
    open_url "https://www.figma.com/settings"
    step "Scroll to 'Personal access tokens'."
    step "Click 'Generate new token', name it 'qa-ai'."
    step "Copy the token — it is shown only once."
    printf '\n'
  fi
  ask_secret FIGMA_API_KEY "Paste the Figma token:"
  add_mcp figma -e "FIGMA_API_KEY=$FIGMA_API_KEY" -- npx -y figma-developer-mcp --stdio
fi
pause

# ── Stage 6: Browser + Jira connector ─────────────────────────────────────
stage "Browser control and Jira connector"
say "Playwright drives the browser for screenshots and bug evidence."
say "It needs no password."
printf '\n'
add_mcp playwright -- npx -y @playwright/mcp@latest --browser chrome
printf '\n'
say "Jira also needs the Atlassian connector, which is switched on in your"
say "browser rather than here."
printf '\n'
open_url "https://claude.ai/settings/connectors"
step "Find 'Atlassian' in the list and click Connect."
step "Approve the access request."
if ! confirm "Done — is Atlassian showing as connected?"; then
  SKIPPED+=("Atlassian connector at claude.ai/settings/connectors")
fi
pause

# ── Stage 7: GitHub ───────────────────────────────────────────────────────
stage "GitHub"
say "Used to push your test case files and open pull requests."
say "The repo is public, so you only need this to push your own work."
printf '\n'
if command -v gh >/dev/null 2>&1; then
  note "gh is already installed."
else
  say "Installing the GitHub CLI ..."
  if (( DRY_RUN )); then
    printf '  %s[dry-run]%s would brew install gh\n' "$YELLOW" "$RESET"
  elif command -v brew >/dev/null 2>&1 && brew install gh >/dev/null 2>&1; then
    printf '  %s✓ installed%s gh\n' "$GREEN" "$RESET"
  else
    warn "could not install gh automatically."
    SKIPPED+=("install gh, then run: gh auth login")
  fi
fi
printf '\n'
if _gh_ready && ! reconfigure "GitHub"; then
  note "Keeping the GitHub sign-in already in place."
elif (( DRY_RUN )); then
  printf '  %s[dry-run]%s would sign in to GitHub\n' "$YELLOW" "$RESET"
else
  if ! have_key "a GitHub personal access token"; then
    open_url "https://github.com/settings/tokens"
    step "Click 'Generate new token' → 'Tokens (classic)'."
    step "Name it 'qa-ai', set an expiry."
    step "Tick the 'repo' and 'read:org' scopes."
    step "Click 'Generate token' and copy it — shown only once."
    printf '\n'
  fi
  ask_secret GITHUB_TOKEN "Paste your GitHub token:"
  if [[ -z "$GITHUB_TOKEN" ]]; then
    SKIPPED+=("gh auth login --with-token")
  elif printf '%s' "$GITHUB_TOKEN" | gh auth login --hostname github.com --git-protocol https --with-token >/dev/null 2>&1; then
    gh auth setup-git >/dev/null 2>&1 || true
    printf '  %s✓ signed in%s to GitHub, and git push is wired up\n' "$GREEN" "$RESET"
  else
    warn "GitHub sign-in failed — check the token has the 'repo' scope."
    SKIPPED+=("gh auth login --with-token")
  fi
fi
pause

# ── Stage 8: Check ────────────────────────────────────────────────────────
stage "Checking everything works"
printf '\n'
if .venv/bin/python -c "import jira, googleapiclient, dotenv" 2>/dev/null; then
  printf '  %s✓%s Python packages installed\n' "$GREEN" "$RESET"
else
  warn "Python packages missing — re-run this wizard."
fi
for s in playwright testmo figma google-docs; do
  if _mcp_has "$s"; then
    printf '  %s✓%s %s connected\n' "$GREEN" "$RESET" "$s"
  else
    printf '  %s✗%s %s not connected\n' "$RED" "$RESET" "$s"
  fi
done
if _gh_ready; then
  printf '  %s✓%s GitHub signed in\n' "$GREEN" "$RESET"
else
  printf '  %s✗%s GitHub not signed in\n' "$RED" "$RESET"
fi
if [[ -f "$ENV_FILE" ]] && ! grep -qE '^[A-Z_]+=$|^[A-Z_]+=""$' "$ENV_FILE"; then
  printf '  %s✓%s secrets file filled in\n' "$GREEN" "$RESET"
else
  warn "some values in $ENV_FILE are still blank"
fi
pause

finish
